setGeneric("connection_apihosturl", function(obj, ...) standardGeneric("connection_apihosturl"))
setGeneric("connection_token", function(obj, ...) standardGeneric("connection_token"))
setGeneric("get_sample_metadata", function(obj, ...) standardGeneric("get_sample_metadata"))
setGeneric("get_sample_name", function(obj, ...) standardGeneric("get_sample_name"))
setGeneric("get_analysis_name", function(obj, ...) standardGeneric("get_analysis_name"))
setGeneric("get_sample_metadata_json", function(obj, ...) standardGeneric("get_sample_metadata_json"))
setGeneric("get_spectrum_metadata", function(obj, ...) standardGeneric("get_spectrum_metadata"))
setGeneric("get_spectrum_metadata_json", function(obj, ...) standardGeneric("get_spectrum_metadata_json"))
