setGeneric("connection_apihosturl", function(obj, ...) standardGeneric("connection_apihosturl"))
setGeneric("connection_identityurl", function(obj, ...) standardGeneric("connection_identityurl"))
setGeneric("connection_token", function(obj, ...) standardGeneric("connection_token"))
setGeneric("connection_username", function(obj, ...) standardGeneric("connection_username"))
setGeneric("connection_password", function(obj, ...) standardGeneric("connection_password"))
setGeneric("get_sample_metadata", function(obj, ...) standardGeneric("get_sample_metadata"))
setGeneric("get_sample_name", function(obj, ...) standardGeneric("get_sample_name"))
setGeneric("get_sample_id", function(obj, ...) standardGeneric("get_sample_id"))
setGeneric("get_analysis_name", function(obj, ...) standardGeneric("get_analysis_name"))
setGeneric("get_sample_metadata_json", function(obj, ...) standardGeneric("get_sample_metadata_json"))
setGeneric("get_spectrum_metadata", function(obj, ...) standardGeneric("get_spectrum_metadata"))
setGeneric("get_spectrum_metadata_json", function(obj, ...) standardGeneric("get_spectrum_metadata_json"))
setGeneric("get_sample_data", function(obj, ...) standardGeneric("get_sample_data"))
setGeneric("add_sample_id", function(obj, id, ...) standardGeneric("add_sample_id"))
